version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./data:/var/lib/mysql
      - ./backup:/backup
      - ./my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"
