# Используйте официальный образ Debian
FROM debian:latest

# Установите необходимое программное обеспечение, например, SSH и sudo
RUN apt-get update && \
    apt-get -y install openssh-server sudo && \
    apt-get -y install python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Настройка SSH
RUN ssh-keygen -A

# Создание необходимого каталога для SSH
RUN mkdir /run/sshd

# Дополнительные команды для настройки SSH и создания пользователя ansible
RUN useradd -m -s /bin/bash ansible && \
    echo "ansible:ansible" | chpasswd && \
    echo "ansible ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Открытие порта для SSH
EXPOSE 22

# Запуск SSH сервиса при старте контейнера
CMD ["/usr/sbin/sshd", "-D"]
