---
  - name: Download and extract containerd
    get_url:
      url: https://github.com/containerd/containerd/releases/download/v1.7.0/containerd-1.7.0-linux-amd64.tar.gz
      dest: /tmp/containerd-1.7.0-linux-amd64.tar.gz

  - name: Extract containerd archive
    unarchive:
      src: /tmp/containerd-1.7.0-linux-amd64.tar.gz
      dest: /usr/local
      remote_src: yes
      # copy: no

  - name: Install containerd.service
    get_url:
      url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
      dest: /usr/lib/systemd/system/containerd.service
      mode: '0644'

  - name: Reload systemd daemon
    systemd:
      daemon_reload: yes

  - name: Enable and start containerd
    systemd:
      name: containerd
      enabled: yes
      state: started
...