---
  - name: Download k9s
    get_url:
      url: https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz
      dest: /tmp/k9s_Linux_amd64.tar.gz
      validate_certs: no

  - name: Install k9s
    when: ansible_os_family == 'Debian'
    unarchive:
      src: /tmp/k9s_Linux_amd64.tar.gz
      dest: /usr/local/bin/
      remote_src: yes
      extra_opts: ["--no-same-owner"]

  - name: Install k9s
    when: ansible_os_family == 'RedHat'
    unarchive:
      src: /tmp/k9s_Linux_amd64.tar.gz
      dest: /bin
      remote_src: yes
      extra_opts: ["--no-same-owner"]

  - name: Remove temporary files
    file:
      path: /tmp/k9s_Linux_amd64*
      state: absent

...