#!/bin/bash

# Yandex folder_id
export TRF_VAR_folder_id='b1gq0mj5rh4up99offieh'
# Yandex cloud_id
export TRF_VAR_cloud_id='b1gbalrr4suqf48hapk6f'
# Yandex token
export TRF_VAR_token='y0_AgAAAABkbnEbAATuwQAAAADxF_wYlhaOLhxbTj8moknJAorbzLPjd7yE'
# SSH public key (Linux машины) где запускается проект
export TRF_VAR_trf_mng_public_key=$(cat /root/.ssh/id_rsa.pub)


# TF_CLI_TIMEOUT=15m - Время прерывания terraform apply

# Переходим в папку terraform
cd yac-terraform
# Запуск Terraform с переменными
# TF_CLI_TIMEOUT=15m - Время прерывания terraform apply
TF_CLI_TIMEOUT=15m terraform apply \
 -var "trf_folder_id=${TRF_VAR_folder_id}" \
 -var "trf_cloud_id=${TRF_VAR_cloud_id}" \
 -var "trf_token=${TRF_VAR_token}" \
 -var "trf_mng_vm_master_public_key=${TRF_VAR_trf_mng_public_key}" \
 -var "trf_mng_vm_worker_public_key=${TRF_VAR_trf_mng_public_key}"

# Задержка перед запуском ansible-playbook
echo 'sleep 30'
sleep 30

# Установка ПО на сервера 
cd ..
cd ansible
ansible-galaxy collection install community.kubernetes
ansible-playbook -i hosts  py_test.yml
ansible-playbook -i hosts  start_role.yml

# Установка правил фаервол
# ansible-playbook -i hosts  security_group.yml
