#!/bin/bash

# Yandex folder_id
export TRF_VAR_folder_id='XXXXXXXXXXXXXXXXXX'
# Yandex cloud_id
export TRF_VAR_cloud_id='XXXXXXXXXXXXXXXXXX'
# Yandex token
export TRF_VAR_token='XXXXXXXXXXXXXXXXXX'
# SSH public key (Linux машины) где запускается проект
export TRF_VAR_trf_mng_public_key=$(cat /root/.ssh/id_rsa.pub)

# TF_CLI_TIMEOUT=15m - Время прерывания terraform apply

# Переходим в папку terraform
cd src/terraform
TF_CLI_TIMEOUT=15m terraform apply \
 -var "trf_folder_id=${TRF_VAR_folder_id}" \
 -var "trf_cloud_id=${TRF_VAR_cloud_id}" \
 -var "trf_token=${TRF_VAR_token}"
