version: '3.1'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pgbackups:/backups
    ports:
      - "5432:5432"

