# Настройка clickhouse
- hosts: clickhouse
  become: true
  tags:
    - install
  roles:
    - clickhouse

# Установка vector
- hosts: vector
  become: true
  roles:
    - vector
  
# Установка lighthouse
- hosts: lighthouse
  become: true
  roles:
    - lighthouse
